USE [master]
GO

/****** Object:  Database [ChoDoiDo]    Script Date: 4/16/2022 8:36:55 PM ******/
CREATE DATABASE [ChoDoiDo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ChoDoiDo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ChoDoiDo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ChoDoiDo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ChoDoiDo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ChoDoiDo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ChoDoiDo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ChoDoiDo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ChoDoiDo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ChoDoiDo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ChoDoiDo] SET ARITHABORT OFF 
GO

ALTER DATABASE [ChoDoiDo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ChoDoiDo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ChoDoiDo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ChoDoiDo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ChoDoiDo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ChoDoiDo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ChoDoiDo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ChoDoiDo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ChoDoiDo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ChoDoiDo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ChoDoiDo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ChoDoiDo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ChoDoiDo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ChoDoiDo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ChoDoiDo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ChoDoiDo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ChoDoiDo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ChoDoiDo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ChoDoiDo] SET  MULTI_USER 
GO

ALTER DATABASE [ChoDoiDo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ChoDoiDo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ChoDoiDo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ChoDoiDo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ChoDoiDo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ChoDoiDo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ChoDoiDo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ChoDoiDo] SET  READ_WRITE 
GO


